from datetime import datetime, timedelta
from typing import List, Dict, Any

# Expanded predefined templates: 3 unique grant programs per funder (total 24 grants)
FUNDER_TEMPLATES: Dict[str, List[Dict[str, Any]]] = {
    "DST": [
        {
            "funder": "Department of Science & Technology (DST)",
            "title": "Science and Heritage Research Initiative (SHRI)",
            "description": "Supports research and development activities aimed at the conservation of heritage objects, traditional crafts, and agricultural practices using modern scientific and technological tools.",
            "budget_min": 1000000,
            "budget_max": 5000000,
            "cause_areas": ["Research", "Education"],
            "schedule_vii_categories": ["Promotion of Education", "Science & Technology"],
            "eligible_org_types": ["NGO", "Research Group"],
            "funding_type_offered": ["Research", "Equipment"],
            "geography": "National",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "<10L",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "NGO Darpan Certificate", "12A/80G Certificate", "3 Years Audited Financials", "Detailed Project Report (DPR)"],
            "application_url": "https://dst.gov.in/call-for-proposals",
            "source_portal": "DST Call for Proposals Portal"
        },
        {
            "funder": "Department of Science & Technology (DST)",
            "title": "Sophisticated Analytical Instrument Facilities (SAIF) Support",
            "description": "Funding support to NGOs and academic labs for installing advanced research instruments, supporting local researchers, and conducting technical skill-building workshops.",
            "budget_min": 3000000,
            "budget_max": 12000000,
            "cause_areas": ["Research", "Education"],
            "schedule_vii_categories": ["Science & Technology"],
            "eligible_org_types": ["Research Group", "NGO"],
            "funding_type_offered": ["Equipment", "Research"],
            "geography": "National",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Society", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "NGO Darpan ID", "12A/80G Registration", "Audited Financials", "Lab Space Feasibility Report"],
            "application_url": "https://dst.gov.in/saif-calls",
            "source_portal": "DST SAIF Portal"
        },
        {
            "funder": "Department of Science & Technology (DST)",
            "title": "Science and Technology for Women (STW) Scheme",
            "description": "Promotes development and adaptation of science-led technologies to reduce drudgery, improve healthcare, and create micro-livelihoods for rural and semi-urban women.",
            "budget_min": 1500000,
            "budget_max": 4500000,
            "cause_areas": ["Research", "Women Empowerment", "Rural Development"],
            "schedule_vii_categories": ["Gender Equality", "Rural Development", "Science & Technology"],
            "eligible_org_types": ["NGO", "Community Org"],
            "funding_type_offered": ["Project", "Research"],
            "geography": "Rural India",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "<10L",
            "eligible_legal_entities": ["Society", "Trust"],
            "required_documents": ["Registration Certificate", "NGO Darpan ID", "12A/80G Certificate", "3 Years Audited Financials", "Community Engagement Proof"],
            "application_url": "https://dst.gov.in/stw-scheme",
            "source_portal": "DST Social Equity Portal"
        }
    ],
    "BIRAC": [
        {
            "funder": "Biotechnology Industry Research Assistance Council (BIRAC)",
            "title": "Biotechnology Ignition Grant (BIG) Scheme",
            "description": "BIRAC invites proposals from innovators and biotech startups for the BIG scheme. The grant supports high-risk, high-impact innovations in healthcare, agriculture, and sanitation.",
            "budget_min": 2500000,
            "budget_max": 5000000,
            "cause_areas": ["Healthcare", "Research", "Environment"],
            "schedule_vii_categories": ["Healthcare", "Science & Technology", "Environmental Sustainability"],
            "eligible_org_types": ["Social Startup", "Research Group", "NGO"],
            "funding_type_offered": ["Project", "Research"],
            "geography": "National",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "<10L",
            "eligible_legal_entities": ["Section 8 Company", "Society", "Trust"],
            "required_documents": ["Registration Certificate", "NGO Darpan Certificate", "12A/80G Certificate", "Audited Financials", "IP Ownership Affidavit", "Methodology Plan"],
            "application_url": "https://birac.nic.in/desc_new.php?id=305",
            "source_portal": "BIRAC Innovation Portal"
        },
        {
            "funder": "Biotechnology Industry Research Assistance Council (BIRAC)",
            "title": "Social Innovation Programme (SPARSH) - Maternal Health Focus",
            "description": "Supports product development and clinical validation of affordable healthcare technologies addressing maternal health, infant malnutrition, and clean drinking water in rural communities.",
            "budget_min": 1500000,
            "budget_max": 4000000,
            "cause_areas": ["Healthcare", "Research", "Rural Development"],
            "schedule_vii_categories": ["Healthcare", "Rural Development"],
            "eligible_org_types": ["NGO", "Social Startup"],
            "funding_type_offered": ["Project", "Research"],
            "geography": "Aspirational Districts",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "<10L",
            "eligible_legal_entities": ["Section 8 Company", "Society", "Trust"],
            "required_documents": ["Registration Certificate", "NGO Darpan Registration", "12A/80G Certificate", "Audited Financials", "Clinical Partner Consent Form"],
            "application_url": "https://birac.nic.in/sparsh",
            "source_portal": "BIRAC SPARSH Database"
        },
        {
            "funder": "Biotechnology Industry Research Assistance Council (BIRAC)",
            "title": "Sustainable Entrepreneurship and Enterprise Development (SEED) Fund",
            "description": "Provides equity/grant funding to biotech ventures and non-profit research incubators focusing on industrial waste-to-value conversions and organic agricultural technologies.",
            "budget_min": 3000000,
            "budget_max": 10000000,
            "cause_areas": ["Environment", "Research"],
            "schedule_vii_categories": ["Environmental Sustainability", "Science & Technology"],
            "eligible_org_types": ["Social Startup", "Research Group"],
            "funding_type_offered": ["Project", "Research"],
            "geography": "National",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Section 8 Company", "Society"],
            "required_documents": ["Registration Certificate", "12A/80G Registration", "Audited Financials", "Business Plan Proposal", "Pitch Deck Document"],
            "application_url": "https://birac.nic.in/seed-fund",
            "source_portal": "BIRAC Enterprise Portal"
        }
    ],
    "MSJE": [
        {
            "funder": "Ministry of Social Justice and Empowerment",
            "title": "Atal Vayo Abhyuday Yojana (AVYAY) for Senior Citizens",
            "description": "Financial assistance to registered NGOs and Trusts running senior citizen homes, day care centers, and mobile medical units. Promotes active and healthy ageing in rural districts.",
            "budget_min": 500000,
            "budget_max": 2000000,
            "cause_areas": ["Healthcare", "Rural Development", "Other"],
            "schedule_vii_categories": ["Healthcare", "Rural Development", "Senior Citizens Welfare"],
            "eligible_org_types": ["NGO"],
            "funding_type_offered": ["Project", "Operational"],
            "geography": "Rural India",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "<10L",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "NGO Darpan Certificate", "12A/80G Certificate", "3 Years Audited Financials", "District Social Welfare Officer Recommendation"],
            "application_url": "https://socialjustice.gov.in/schemes",
            "source_portal": "MSJE Portal"
        },
        {
            "funder": "Ministry of Social Justice and Empowerment",
            "title": "Nasha Mukt Bharat Abhiyaan (NMBA) Community Grants",
            "description": "Supports local awareness campaigns, de-addiction therapy setups, and community counseling operations in high-risk districts to build a drug-free India.",
            "budget_min": 300000,
            "budget_max": 1500000,
            "cause_areas": ["Healthcare", "Other"],
            "schedule_vii_categories": ["Healthcare", "Reducing Inequalities"],
            "eligible_org_types": ["NGO", "Community Org"],
            "funding_type_offered": ["Project", "Operational"],
            "geography": "High-risk Districts",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "<10L",
            "eligible_legal_entities": ["Society", "Trust"],
            "required_documents": ["Registration Certificate", "NGO Darpan ID", "12A/80G Certificate", "Annual Progress Report", "Staff Qualification List"],
            "application_url": "https://socialjustice.gov.in/nmba",
            "source_portal": "MSJE NMBA Portal"
        },
        {
            "funder": "Ministry of Social Justice and Empowerment",
            "title": "Skill Development Training for Transgender & Marginalized Groups",
            "description": "Funding to vocational institutes and NGOs implementing retail, computer training, and entrepreneurship skills for marginalized and transgender communities.",
            "budget_min": 800000,
            "budget_max": 3000000,
            "cause_areas": ["Education", "Other"],
            "schedule_vii_categories": ["Promotion of Education", "Reducing Inequalities"],
            "eligible_org_types": ["NGO", "Research Group"],
            "funding_type_offered": ["Project", "Operational"],
            "geography": "State Capitals",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": True,
            "requires_csr_1": False,
            "min_turnover_range": "<10L",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "NGO Darpan Registration Certificate", "12A/80G Certificate", "3 Years Audit Reports", "Course Syllabus Details"],
            "application_url": "https://socialjustice.gov.in/skill-dev",
            "source_portal": "MSJE Skill Dev Portal"
        }
    ],
    "TATA_TRUSTS": [
        {
            "funder": "Tata Trusts",
            "title": "Institutional Grant for Primary Healthcare & Education Services",
            "description": "Tata Trusts invites proposals from organizations working on primary healthcare clinics, water hygiene (WASH), and elementary education in aspirational districts.",
            "budget_min": 1000000,
            "budget_max": 7500000,
            "cause_areas": ["Healthcare", "Education", "Rural Development"],
            "schedule_vii_categories": ["Healthcare", "Promotion of Education", "Rural Development"],
            "eligible_org_types": ["NGO", "Community Org"],
            "funding_type_offered": ["Project", "Operational", "Equipment"],
            "geography": "Aspirational Districts",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": False,
            "requires_csr_1": True,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Trust", "Society", "Section 8 Company"],
            "required_documents": ["Trust Deed / Registration Certificate", "12A/80G Registration", "CSR-1 Certificate", "3 Years Audited Financials", "Board Resolution"],
            "application_url": "https://www.tatatrusts.org/our-contributions/grants",
            "source_portal": "Tata Trusts Grants Portal"
        },
        {
            "funder": "Tata Trusts",
            "title": "Aspirational Districts Digital Education Improvement Initiative",
            "description": "Focuses on providing smart infrastructure, teacher capacity building, and digital learning modules for government secondary school students in backward rural areas.",
            "budget_min": 2000000,
            "budget_max": 8000000,
            "cause_areas": ["Education"],
            "schedule_vii_categories": ["Promotion of Education"],
            "eligible_org_types": ["NGO"],
            "funding_type_offered": ["Project", "Equipment"],
            "geography": "Rural Schools",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": False,
            "requires_csr_1": True,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Trust", "Society", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "CSR-1 Registration Certificate", "Audit Statements", "School Permission Letter"],
            "application_url": "https://www.tatatrusts.org/digital-edu",
            "source_portal": "Tata Trusts Education Portal"
        },
        {
            "funder": "Tata Trusts",
            "title": "Sustainable Agriculture & Rainwater Harvesting Grant",
            "description": "Funding to scale up check dam constructions, promote micro-irrigation systems, and train smallholder farmers in drought-resilient crop techniques.",
            "budget_min": 3000000,
            "budget_max": 15000000,
            "cause_areas": ["Environment", "Rural Development"],
            "schedule_vii_categories": ["Environmental Sustainability", "Rural Development"],
            "eligible_org_types": ["NGO", "Community Org"],
            "funding_type_offered": ["Project"],
            "geography": "Drought-prone Blocks",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": False,
            "requires_csr_1": True,
            "min_turnover_range": "50L-1Cr",
            "eligible_legal_entities": ["Trust", "Society"],
            "required_documents": ["Trust Deed / Registration Certificate", "12A/80G Certificate", "CSR-1 Registration", "3 Years Audited Financials", "Land Ownership / NOC Documents"],
            "application_url": "https://www.tatatrusts.org/agri-water",
            "source_portal": "Tata Trusts Water & Livelihoods Database"
        }
    ],
    "FORD_FOUNDATION": [
        {
            "funder": "Ford Foundation India",
            "title": "Gender Equality and Social Justice Grant",
            "description": "Supporting organizations building capacity for rural women leadership, addressing domestic violence, and creating economic opportunities for historically disadvantaged communities.",
            "budget_min": 2500000,
            "budget_max": 10000000,
            "cause_areas": ["Women Empowerment", "Other"],
            "schedule_vii_categories": ["Gender Equality", "Women Empowerment", "Reducing Inequalities"],
            "eligible_org_types": ["NGO", "Community Org", "Research Group"],
            "funding_type_offered": ["Project", "Operational", "Research"],
            "geography": "National",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": "50L-1Cr",
            "eligible_legal_entities": ["Trust", "Society", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "Valid FCRA Registration Certificate", "FCRA-designated Bank Account Details", "Audited Financials"],
            "application_url": "https://www.fordfoundation.org/work/our-grants",
            "source_portal": "Ford Foundation Grants database"
        },
        {
            "funder": "Ford Foundation India",
            "title": "Civic Space & Human Rights Capacity Development",
            "description": "Supports legal aid networks, human rights education groups, and marginalized community organizations to build awareness of fundamental rights and constitutional liberties.",
            "budget_min": 4000000,
            "budget_max": 15000000,
            "cause_areas": ["Other"],
            "schedule_vii_categories": ["Reducing Inequalities"],
            "eligible_org_types": ["NGO", "Research Group"],
            "funding_type_offered": ["Project", "Operational"],
            "geography": "National",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": "50L-1Cr",
            "eligible_legal_entities": ["Trust", "Society", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "FCRA Certificate", "Audit Report Checklist", "Board of Trustees Profile"],
            "application_url": "https://www.fordfoundation.org/civic-space",
            "source_portal": "Ford Foundation Human Rights Portal"
        },
        {
            "funder": "Ford Foundation India",
            "title": "Future of Workers in the Informal Economy",
            "description": "Invests in policy research and capacity development for grassroots coalitions organizing migrant workers, domestic workers, and gig workers in India's metropolitan hubs.",
            "budget_min": 5000000,
            "budget_max": 20000000,
            "cause_areas": ["Research", "Rural Development", "Other"],
            "schedule_vii_categories": ["Rural Development", "Reducing Inequalities"],
            "eligible_org_types": ["Research Group", "NGO"],
            "funding_type_offered": ["Project", "Research"],
            "geography": "Metro Cities",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": ">1Cr",
            "eligible_legal_entities": ["Society", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "FCRA Registration Document", "3 Years Audited Financials", "Research Methodology Framework"],
            "application_url": "https://www.fordfoundation.org/informal-workers",
            "source_portal": "Ford Foundation Work & Livelihoods Database"
        }
    ],
    "INFOSYS_CSR": [
        {
            "funder": "Infosys Foundation",
            "title": "Infosys Foundation Primary Education & Digital Literacy Grant",
            "description": "Funding is provided for building smart classrooms, digital training labs in rural government schools, and creating open-source learning resources.",
            "budget_min": 5000000,
            "budget_max": 25000000,
            "cause_areas": ["Education", "Environment"],
            "schedule_vii_categories": ["Promotion of Education", "Environmental Sustainability"],
            "eligible_org_types": ["NGO", "Section 8 Company"],
            "funding_type_offered": ["Project", "Equipment"],
            "geography": "National",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": False,
            "requires_csr_1": True,
            "min_turnover_range": ">1Cr",
            "eligible_legal_entities": ["Section 8 Company", "Trust", "Society"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "CSR-1 Certificate", "3 Years Audited Financials", "Tax Clearance Certificate"],
            "application_url": "https://www.infosys.com/infosys-foundation/grants.html",
            "source_portal": "Infosys CSR Portal"
        },
        {
            "funder": "Infosys Foundation",
            "title": "Aarohan Social Innovation Award for Healthcare Solutions",
            "description": "Grant awards to NGOs and innovators developing low-cost diagnostic devices, mobile clinics, and healthcare solutions for under-funded municipal hospitals.",
            "budget_min": 2000000,
            "budget_max": 10000000,
            "cause_areas": ["Healthcare", "Research"],
            "schedule_vii_categories": ["Healthcare", "Science & Technology"],
            "eligible_org_types": ["NGO", "Social Startup"],
            "funding_type_offered": ["Project", "Equipment"],
            "geography": "Tier-2/3 Cities",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": False,
            "requires_csr_1": True,
            "min_turnover_range": "50L-1Cr",
            "eligible_legal_entities": ["Section 8 Company", "Trust", "Society"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "CSR-1 Registration", "Audit Reports", "Clinical Validation Certificate"],
            "application_url": "https://www.infosys.com/infosys-foundation/aarohan.html",
            "source_portal": "Infosys Aarohan Awards Portal"
        },
        {
            "funder": "Infosys Foundation",
            "title": "Environment Conservation & Solid Waste Management Initiative",
            "description": "Funding support to establish zero-waste municipal clusters, setup automated compost units, and restore polluted urban lake ecosystems.",
            "budget_min": 4000000,
            "budget_max": 15000000,
            "cause_areas": ["Environment"],
            "schedule_vii_categories": ["Environmental Sustainability"],
            "eligible_org_types": ["NGO", "Section 8 Company"],
            "funding_type_offered": ["Project"],
            "geography": "Metropolitan Cities",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": False,
            "requires_ngo_darpan": False,
            "requires_csr_1": True,
            "min_turnover_range": ">1Cr",
            "eligible_legal_entities": ["Section 8 Company", "Trust", "Society"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "CSR-1 Certificate", "3 Years Audited Financials", "Detailed Municipal NOC"],
            "application_url": "https://www.infosys.com/infosys-foundation/environment-grants.html",
            "source_portal": "Infosys Environment Grants Database"
        }
    ],
    "UN_WOMEN": [
        {
            "funder": "UN Women India",
            "title": "Empowering Rural Women Entrepreneurs through Digital Literacy",
            "description": "UN Women invites proposals to establish support centers and training programs for women-led micro-enterprises in agricultural districts, supporting digital payment integration.",
            "budget_min": 1500000,
            "budget_max": 5000000,
            "cause_areas": ["Women Empowerment", "Rural Development"],
            "schedule_vii_categories": ["Gender Equality", "Rural Development", "Women Empowerment"],
            "eligible_org_types": ["NGO", "Community Org"],
            "funding_type_offered": ["Project", "Operational"],
            "geography": "State-specific (Maharashtra, Gujarat, Rajasthan)",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "Valid FCRA Certificate", "3 Years Audited Financials", "Detailed Budget Workbook"],
            "application_url": "https://www.unwomen.org/en/about-us/programme-implementation",
            "source_portal": "UN Women procurement & partners portal"
        },
        {
            "funder": "UN Women India",
            "title": "Ending Violence Against Women & Safety in Public Spaces (EVAW)",
            "description": "Supports grassroots NGOs building community vigilance panels, safe transit initiatives for working women, and gender-sensitization workshops for local transport services.",
            "budget_min": 1000000,
            "budget_max": 3500000,
            "cause_areas": ["Women Empowerment", "Other"],
            "schedule_vii_categories": ["Gender Equality", "Women Empowerment"],
            "eligible_org_types": ["NGO", "Community Org"],
            "funding_type_offered": ["Project", "Operational"],
            "geography": "Selected Urban Clusters",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "Valid FCRA Registration", "Audited Accounts Checksheets", "Community Surveys Summary"],
            "application_url": "https://www.unwomen.org/india/evaw",
            "source_portal": "UN Women Safety Division Database"
        },
        {
            "funder": "UN Women India",
            "title": "Women's Leadership in Climate Change Adaptation",
            "description": "Supports rural non-profits strengthening women-led disaster response committees, promoting climate-resilient water storage, and building seed banks managed by women farmers.",
            "budget_min": 2000000,
            "budget_max": 6000000,
            "cause_areas": ["Women Empowerment", "Environment", "Rural Development"],
            "schedule_vii_categories": ["Gender Equality", "Environmental Sustainability", "Rural Development"],
            "eligible_org_types": ["NGO", "Community Org"],
            "funding_type_offered": ["Project"],
            "geography": "Coastal & Drought Regions",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "FCRA Registration Document", "Audit Statements", "Project Site GPS Coordinates"],
            "application_url": "https://www.unwomen.org/india/climate-adaptation",
            "source_portal": "UN Women Environmental Registry"
        }
    ],
    "UNDP": [
        {
            "funder": "UNDP India",
            "title": "Climate Resilience and Community-led Livelihoods Support",
            "description": "Grants to support local NGOs implementing decentralized rainwater harvesting, solar irrigation networks, and agro-forestry livelihoods for smallholder farmers.",
            "budget_min": 2000000,
            "budget_max": 6000000,
            "cause_areas": ["Environment", "Rural Development"],
            "schedule_vii_categories": ["Environmental Sustainability", "Rural Development"],
            "eligible_org_types": ["NGO", "Research Group", "Community Org"],
            "funding_type_offered": ["Project", "Research", "Travel"],
            "geography": "National",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "Valid FCRA Certificate", "Audited Financials", "UN Partner Portal Registration ID"],
            "application_url": "https://www.undp.org/india/procurement",
            "source_portal": "UNDP Partner Portal"
        },
        {
            "funder": "UNDP India",
            "title": "Plastic Waste Management and Circular Economy Initiative",
            "description": "Supports local partnerships establishing dry waste material recovery centers, integrating informal waste-pickers into municipal setups, and setting up plastic recycling hubs.",
            "budget_min": 3000000,
            "budget_max": 10000000,
            "cause_areas": ["Environment", "Rural Development"],
            "schedule_vii_categories": ["Environmental Sustainability", "Reducing Inequalities"],
            "eligible_org_types": ["NGO", "Community Org"],
            "funding_type_offered": ["Project", "Operational"],
            "geography": "Selected Municipalities",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": "10L-50L",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "FCRA Registration Doc", "3 Years Audited Financials", "Municipal MoU Copy"],
            "application_url": "https://www.undp.org/india/waste-management",
            "source_portal": "UNDP Procurement Portal"
        },
        {
            "funder": "UNDP India",
            "title": "Decentralized Renewable Energy for Rural Health Clinics",
            "description": "Funding to setup solar-panel arrays, lithium-ion battery backups, and energy-efficient medical tools for primary health sub-centers in tribal zones.",
            "budget_min": 5000000,
            "budget_max": 15000000,
            "cause_areas": ["Environment", "Healthcare", "Rural Development"],
            "schedule_vii_categories": ["Environmental Sustainability", "Healthcare", "Rural Development"],
            "eligible_org_types": ["NGO", "Research Group"],
            "funding_type_offered": ["Project", "Equipment"],
            "geography": "Tribal Blocks",
            "requires_audited_financials": True,
            "requires_12a_80g": True,
            "requires_fcra": True,
            "requires_ngo_darpan": False,
            "requires_csr_1": False,
            "min_turnover_range": "50L-1Cr",
            "eligible_legal_entities": ["Society", "Trust", "Section 8 Company"],
            "required_documents": ["Registration Certificate", "12A/80G Certificate", "FCRA Certificate", "Audited Financials", "State Health Department NOC"],
            "application_url": "https://www.undp.org/india/rural-health-energy",
            "source_portal": "UNDP Environment Unit Database"
        }
    ]
}
